const accounts = [
  {id:'sim-tl-784215',platform:'TL',broker:'TradeLocker',accountNumber:'784215',environment:'Demo',name:'TradeLocker · Account 784215',balance:5000,equity:5068.42,dailyPl:68.42,symbols:[
    ['BTCUSD','Crypto',64210.4],['ETHUSD','Crypto',2754.2],['SOLUSD','Crypto',148.63],['BNBUSD','Crypto',603.4],['XAUUSD','Commodity',2431.18],['USOIL','Commodity',74.22],['NAS100','Index',19648.1],['US30','Index',40810],['EURUSD','Forex',1.11642],['GBPUSD','Forex',1.30415]
  ]},
  {id:'tl-784319',platform:'TL',broker:'TradeLocker',accountNumber:'784319',environment:'Demo',name:'TradeLocker · Account 784319',balance:25000,equity:25142.80,dailyPl:142.80,symbols:[
    ['BTCUSD','Crypto',64218.8],['ETHUSD','Crypto',2756.1],['XAUUSD','Commodity',2431.42],['XAGUSD','Commodity',29.86],['NAS100','Index',19651.2],['US30','Index',40818],['SPX500','Index',5561.5],['EURUSD','Forex',1.11645],['GBPJPY','Forex',189.42],['USDJPY','Forex',145.31]
  ]},
  {id:'sim-mt5-51003821',platform:'MT5',broker:'MetaTrader 5',accountNumber:'51003821',environment:'Demo',name:'MetaTrader 5 · Account 51003821',balance:10000,equity:9976.15,dailyPl:-23.85,symbols:[
    ['BTCUSD.pro','Crypto',64206.1],['ETHUSD.pro','Crypto',2753.7],['GOLD','Commodity',2431.05],['XAGUSD','Commodity',29.84],['USTEC','Index',19645.6],['DJ30','Index',40802],['GER40','Index',18532.4],['EURUSD.a','Forex',1.11639],['USDJPY.a','Forex',145.28],['AUDUSD.a','Forex',0.67612]
  ]},
  {id:'mt5-51004192',platform:'MT5',broker:'MetaTrader 5',accountNumber:'51004192',environment:'Demo',name:'MetaTrader 5 · Account 51004192',balance:50000,equity:50312.05,dailyPl:312.05,symbols:[
    ['BTCUSD.r','Crypto',64211.2],['ETHUSD.r','Crypto',2754.9],['XAUUSD.r','Commodity',2431.31],['USOIL.r','Commodity',74.25],['US100.r','Index',19649.7],['US30.r','Index',40812],['EURUSD.r','Forex',1.11643],['GBPUSD.r','Forex',1.30418],['USDJPY.r','Forex',145.30],['AUDUSD.r','Forex',0.67618]
  ]}
];

const state={account:accounts[0],symbol:null,series:{},proposal:null,alerts:[],open:1,pending:0,scanResults:[],top3:[],connector:{tested:false},installPrompt:null};
const $=id=>document.getElementById(id);
const fmt=(n,symbol)=>{if(symbol?.includes('USD')&&n<10)return n.toFixed(5);if(n<100)return n.toFixed(2);if(n<1000)return n.toFixed(2);return n.toLocaleString(undefined,{maximumFractionDigits:2})};
const now=()=>new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});

function seedFromString(str){let h=2166136261;for(const c of str){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return ()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function makeSeries(symbol,tf,base){const rng=seedFromString(symbol+tf+state.account.id);const pts=[];let p=base*(.96+rng()*.08);const volScale={"4h":.011,"1h":.006,"15m":.003,"5m":.0018}[tf];for(let i=0;i<72;i++){const drift=(rng()-.48)*base*volScale;const o=p;const c=Math.max(base*.25,o+drift);const spread=Math.abs(drift)+base*volScale*(.2+rng()*.6);const h=Math.max(o,c)+spread*rng();const l=Math.min(o,c)-spread*rng();const v=Math.floor(150+900*rng()+Math.abs(c-o)/Math.max(base*.0001,1)*350);pts.push({o,h,l,c,v});p=c}const closes=pts.map(x=>x.c);const rsis=calcRSI(closes,14);pts.forEach((x,i)=>x.rsi=rsis[i]);return pts}
function makeBundle(s){const bundle={};['4h','1h','15m','5m'].forEach(tf=>bundle[tf]=makeSeries(s[0],tf,s[2]));return bundle}
function calcRSI(vals,n){const out=new Array(vals.length).fill(50);if(vals.length<=n)return out;let gain=0,loss=0;for(let i=1;i<=n;i++){const d=vals[i]-vals[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0)}gain/=n;loss/=n;out[n]=100-(100/(1+(loss?gain/loss:100)));for(let i=n+1;i<vals.length;i++){const d=vals[i]-vals[i-1];gain=(gain*(n-1)+Math.max(d,0))/n;loss=(loss*(n-1)+Math.max(-d,0))/n;out[i]=100-(100/(1+(loss?gain/loss:100)))}for(let i=0;i<n;i++)out[i]=out[n]||50;return out}

function drawChart(canvas,data){const dpr=window.devicePixelRatio||1;const rect=canvas.getBoundingClientRect();canvas.width=Math.max(1,rect.width*dpr);canvas.height=Math.max(1,rect.height*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const W=rect.width,H=rect.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#0b111a';ctx.fillRect(0,0,W,H);const left=8,right=42,top=18;const priceH=H*.56,volTop=H*.62,volH=H*.13,rsiTop=H*.80,rsiH=H*.16;const recent=data.slice(-48);const hi=Math.max(...recent.map(x=>x.h)),lo=Math.min(...recent.map(x=>x.l));const vmax=Math.max(...recent.map(x=>x.v));const xStep=(W-left-right)/recent.length;const py=v=>top+(hi-v)/(hi-lo||1)*(priceH-top);ctx.strokeStyle='#1b2736';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=top+i*(priceH-top)/4;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(W-right,y);ctx.stroke()}recent.forEach((c,i)=>{const x=left+i*xStep+xStep/2;const up=c.c>=c.o;ctx.strokeStyle=up?'#2bc48a':'#ff667a';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(x,py(c.h));ctx.lineTo(x,py(c.l));ctx.stroke();const y1=py(Math.max(c.o,c.c)),y2=py(Math.min(c.o,c.c));ctx.fillRect(x-xStep*.28,y1,Math.max(1,xStep*.56),Math.max(1,y2-y1));const vh=(c.v/vmax)*volH;ctx.globalAlpha=.45;ctx.fillRect(x-xStep*.28,volTop+volH-vh,Math.max(1,xStep*.56),vh);ctx.globalAlpha=1});ctx.strokeStyle='#354a68';ctx.beginPath();ctx.moveTo(left,rsiTop);ctx.lineTo(W-right,rsiTop);ctx.moveTo(left,rsiTop+rsiH);ctx.lineTo(W-right,rsiTop+rsiH);ctx.stroke();const rsiY=v=>rsiTop+(100-v)/100*rsiH;ctx.strokeStyle='#b078ff';ctx.lineWidth=1.5;ctx.beginPath();recent.forEach((c,i)=>{const x=left+i*xStep+xStep/2,y=rsiY(c.rsi);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.strokeStyle='#53466f';[30,70].forEach(v=>{ctx.beginPath();ctx.moveTo(left,rsiY(v));ctx.lineTo(W-right,rsiY(v));ctx.stroke()});ctx.fillStyle='#7f93ae';ctx.font='10px system-ui';ctx.textAlign='right';ctx.fillText(fmt(hi,state.symbol?.[0]),W-4,top+5);ctx.fillText(fmt(lo,state.symbol?.[0]),W-4,priceH);ctx.fillText('70',W-4,rsiY(70)+3);ctx.fillText('30',W-4,rsiY(30)+3)}

async function loadAccount(){state.account=accounts.find(a=>a.id===$('accountSelect').value)||accounts[0];state.symbol=state.account.symbols[0];state.open=state.account.platform==='TL'?1:0;state.pending=state.account.platform==='TL'?0:1;state.alerts=[];state.top3=[];state.scanResults=[];renderAccount();renderWatchlist();renderTop3();selectSymbol(state.symbol,false);try{await fetch('/api/select-account',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({account_id:state.account.id})});state.connector.tested=true;renderConversationStatus();addActivity(`Backend route selected: ${state.account.broker} ${state.account.accountNumber}.`,'success')}catch(e){addActivity(`Loaded local ${state.account.broker} account ${state.account.accountNumber}.`)}addChat('ai',`Active account changed to ${state.account.broker} account ${state.account.accountNumber}. Future approvals in this demo are routed only to that selected account.`)}
function renderAccount(){$('balance').textContent='$'+state.account.balance.toLocaleString(undefined,{minimumFractionDigits:2});$('equity').textContent='$'+state.account.equity.toLocaleString(undefined,{minimumFractionDigits:2});$('dailyPl').textContent=(state.account.dailyPl>=0?'+':'-')+'$'+Math.abs(state.account.dailyPl).toFixed(2);$('dailyPl').className=state.account.dailyPl>=0?'positive':'negative';$('openCount').textContent=state.open;$('pendingCount').textContent=state.pending;$('alertCount').textContent=state.alerts.length;$('watchlistTitle').textContent=state.account.platform==='MT5'?'Market Watch':'Broker Symbols';$('brokerPill').textContent=state.account.broker;$('platformMark').textContent=state.account.platform;$('activeAccountLabel').textContent=`${state.account.broker} · Account ${state.account.accountNumber}`;$('activeEnvironment').textContent=state.account.environment.toUpperCase();$('activeWatchSource').textContent=state.account.platform==='MT5'?'MetaTrader Market Watch':'TradeLocker Broker Symbols';$('watchAccountMini').innerHTML=`<span>${state.account.broker}</span><strong>Account ${state.account.accountNumber}</strong>`;renderConversationStatus()}
function renderConversationStatus(){const ok=state.connector.tested;$('conversationStatus').textContent=ok?'ChatGPT connector ready':'ChatGPT connector local demo';$('conversationStatus').className=ok?'connection-on':'connection-off';$('linkPill').textContent=ok?'Ready':'Local demo';$('linkPill').className=ok?'pill':'pill neutral'}
function renderWatchlist(){const list=$('watchlist');list.innerHTML='';state.account.symbols.forEach(s=>{const change=((seedFromString(s[0]+'chg'+state.account.id)()-.48)*2.2);const el=document.createElement('div');el.className='watch-item'+(state.symbol?.[0]===s[0]?' active':'');el.innerHTML=`<div><div class="watch-symbol">${s[0]}</div><div class="watch-type">${s[1]}</div></div><div><div class="watch-price">${fmt(s[2],s[0])}</div><div class="watch-change ${change>=0?'positive':'negative'}">${change>=0?'+':''}${change.toFixed(2)}%</div></div>`;el.onclick=()=>selectSymbol(s);list.appendChild(el)});populateAlertSymbols()}
function selectSymbol(s,announce=true){state.symbol=s;state.series=makeBundle(s);const last=state.series['5m'].at(-1).c;$('symbolTitle').textContent=s[0];$('priceTitle').textContent=fmt(last,s[0]);renderWatchlist();drawAll();state.proposal=createProposal(s,state.series);renderProposal();if(announce)addChat('ai',`Loaded ${s[0]} from ${state.account.broker} account ${state.account.accountNumber}. I have 4H, 1H, 15M and 5M candles with volume and RSI ready.`)}
function drawAll(){drawChart($('chart4h'),state.series['4h']);drawChart($('chart1h'),state.series['1h']);drawChart($('chart15m'),state.series['15m']);drawChart($('chart5m'),state.series['5m'])}
function createProposal(s=state.symbol,bundle=state.series){const symbol=s[0],p=bundle['5m'].at(-1).c,r4=bundle['4h'].at(-1).rsi,r1=bundle['1h'].at(-1).rsi,r15=bundle['15m'].at(-1).rsi,r5=bundle['5m'].at(-1).rsi;const avg=(r4*1.2+r1*1.1+r15+r5*.7)/4;const dir=avg>=50?'LONG':'SHORT';const mult=dir==='LONG'?1:-1;const entry=p;const stop=p*(1-mult*.006);const tp1=p*(1+mult*.009);const tp2=p*(1+mult*.016);const alignment=[r4,r1,r15,r5].filter(r=>dir==='LONG'?r>=50:r<50).length;const recent=bundle['15m'].slice(-12);const avgVol=recent.reduce((a,b)=>a+b.v,0)/recent.length;const volRatio=recent.at(-1).v/avgVol;const score=Math.min(94,Math.round(52+alignment*7+Math.abs(avg-50)*.55+Math.max(0,volRatio-1)*8));return{symbol,dir,entry,stop,tp1,tp2,risk:.5,score,r4,r1,r15,r5,volRatio,reason:`${dir==='LONG'?'Bullish':'Bearish'} multi-timeframe alignment across ${alignment}/4 timeframes. 4H RSI ${r4.toFixed(1)}, 1H ${r1.toFixed(1)}, 15M ${r15.toFixed(1)}, 5M ${r5.toFixed(1)}. Latest 15M volume is ${volRatio.toFixed(2)}× its recent average.`}}
function normalizeBackendProposal(row){const bp=row.proposal;return{symbol:bp.symbol,dir:bp.direction==='BUY'?'LONG':'SHORT',score:bp.score,entry:bp.entry,stop:bp.safeLoss,tp1:bp.takeProfit1,tp2:bp.takeProfit2,risk:bp.riskPercent,proposalId:bp.proposalId,r4:bp.evidence.rsis['4H'],r1:bp.evidence.rsis['1H'],r15:bp.evidence.rsis['15M'],r5:bp.evidence.rsis['5M'],volRatio:bp.evidence.volumeRatio15m,reason:`Ranked ${bp.score}% by the connector after reviewing 4H, 1H, 15M and 5M RSI, candle structure and volume.`}}
function openRankedProposal(index,action='open'){const item=state.top3[index];if(!item)return;let s=state.account.symbols.find(x=>x[0]===item.symbol)||[item.symbol,item.assetClass||'Broker',Number(item.proposal.entry||1)];state.symbol=s;state.series=makeBundle(s);state.proposal=item.normalized||normalizeBackendProposal(item);$('symbolTitle').textContent=s[0];$('priceTitle').textContent=fmt(state.series['5m'].at(-1).c,s[0]);renderWatchlist();drawAll();renderProposal();document.querySelector('.proposal-card')?.scrollIntoView({behavior:'smooth',block:'start'});if(action==='exp')explain();if(action==='app')approve(false);if(action==='expapp')approve(true);if(action==='reject')reject();}
function renderTop3(){const box=$('top3List'),status=$('top3Status');if(!state.top3.length){box.innerHTML='<div class="proposal-empty">Tap <b>Scan Everything</b> to rank the three strongest setups on this account.</div>';status.textContent='Run scan';return}status.textContent=`${state.scanResults.length} scanned`;box.innerHTML=state.top3.map((item,i)=>{const p=item.normalized||normalizeBackendProposal(item);const cls=p.dir==='LONG'?'positive':'negative';return `<article class="rank-card"><div class="rank-number">#${i+1}</div><div class="rank-main"><div class="rank-title"><strong>${p.symbol}</strong><span class="${cls}">${p.dir}</span><span class="score-chip">${p.score}%</span></div><div class="rank-route">${state.account.broker} · Account ${state.account.accountNumber}</div><div class="rank-levels"><span>Entry <b>${fmt(p.entry,p.symbol)}</b></span><span>SL <b>${fmt(p.stop,p.symbol)}</b></span><span>TP1 <b>${fmt(p.tp1,p.symbol)}</b></span><span>TP2 <b>${fmt(p.tp2,p.symbol)}</b></span></div><div class="rank-actions"><button class="secondary" data-rank="${i}" data-action="exp">EXP</button><button class="success" data-rank="${i}" data-action="app">APP</button><button class="accent" data-rank="${i}" data-action="expapp">EXP + APP</button><button class="danger" data-rank="${i}" data-action="reject">REJECT</button></div></div></article>`}).join('');box.querySelectorAll('button[data-rank]').forEach(btn=>btn.onclick=()=>openRankedProposal(Number(btn.dataset.rank),btn.dataset.action))}
function renderProposal(){const p=state.proposal;$('proposalHeadline').textContent=`${p.symbol} · ${p.dir} · ${p.score}% setup score`;$('proposalBody').innerHTML=`<div class="proposal-route">Route: <strong>${state.account.broker} · Account ${state.account.accountNumber}</strong></div><div class="trade-grid"><div class="trade-field"><span>Entry</span><strong>${fmt(p.entry,p.symbol)}</strong></div><div class="trade-field"><span>Safe Loss</span><strong>${fmt(p.stop,p.symbol)}</strong></div><div class="trade-field"><span>Take Profit 1</span><strong>${fmt(p.tp1,p.symbol)}</strong></div><div class="trade-field"><span>Take Profit 2</span><strong>${fmt(p.tp2,p.symbol)}</strong></div></div><div class="trade-grid"><div class="trade-field"><span>Risk</span><strong>${p.risk.toFixed(2)}%</strong></div><div class="trade-field"><span>Est. max loss</span><strong>$${(state.account.balance*p.risk/100).toFixed(2)}</strong></div><div class="trade-field"><span>Order Qty / Volume</span><input id="tradeQty" type="number" min="0.01" step="0.01" value="1" style="width:90px"></div><div class="trade-field"><span>Execution</span><strong>Pending approval</strong></div><div class="trade-field"><span>Source</span><strong>${state.account.platform}</strong></div></div>`;$('explanation').classList.add('hidden')}
function explain(){const p=state.proposal;$('explanation').classList.remove('hidden');$('explanation').innerHTML=`<strong>Why this trade</strong><br><br><b>Account:</b> ${state.account.broker} · ${state.account.accountNumber}<br><b>4H:</b> RSI ${p.r4.toFixed(1)} sets the higher-timeframe bias.<br><b>1H:</b> RSI ${p.r1.toFixed(1)} supports the ${p.dir.toLowerCase()} case.<br><b>15M:</b> RSI ${p.r15.toFixed(1)} with volume at ${p.volRatio.toFixed(2)}× recent average.<br><b>5M:</b> RSI ${p.r5.toFixed(1)} provides the execution trigger.<br><b>Risk:</b> ${p.risk.toFixed(2)}% of account balance, with a mandatory stop.<br><br>${p.reason}`;addChat('ai',`Explanation for ${p.symbol}: ${p.reason}`);addActivity(`EXP opened for ${p.symbol}.`)}
async function approve(withExplanation=false){
  if($('executionMode').value==='Analysis Mode'){addChat('ai','Analysis Mode blocks order execution. Switch to Approval Mode to submit an approved order.');addActivity('Order blocked by Analysis Mode.','warn');return}
  if(withExplanation)explain();
  const qty=Number($('tradeQty')?.value||1); if(!(qty>0)){addChat('ai','Enter a valid order quantity/volume before approving.');return}
  try{
    if(!state.proposal.proposalId) throw new Error('This local proposal has no broker proposal ID. Run Scan Everything through the backend first.');
    const r=await fetch('/api/proposals/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({proposal_id:state.proposal.proposalId,qty,use_tp2:false})});
    const data=await r.json(); if(!r.ok) throw new Error(data.detail||'Approval failed');
    if(data.status==='SIMULATED_APPROVED') addChat('ai',`${state.proposal.symbol} approved for ${state.account.broker} account ${state.account.accountNumber}. The server recorded the approval but did not send a broker order because execution is disabled.`);
    else addChat('ai',`${state.proposal.symbol} ${state.proposal.dir} order sent to ${state.account.broker} account ${state.account.accountNumber}. Server status: ${data.status}.`);
    addActivity(`${state.proposal.symbol} approval → ${data.status}.`,'success');
  }catch(e){addChat('ai',`Order not sent: ${e.message}`);addActivity(`Approval blocked: ${e.message}`,'warn')}
}
async function reject(){
  try{if(state.proposal?.proposalId)await fetch('/api/proposals/reject/'+encodeURIComponent(state.proposal.proposalId),{method:'POST'})}catch(e){}
  addChat('ai',`${state.proposal.symbol} trade proposal rejected. No order was sent to account ${state.account.accountNumber}.`);addActivity(`${state.proposal.symbol} proposal rejected.`);state.proposal=createProposal();renderProposal()
}
async function scan(){
  addChat('user','Scan the entire active broker watchlist.');
  $('scanBtn').disabled=true;$('scanBtn').textContent='Scanning all 4 TFs…';if($('mobileScanBtn')){$('mobileScanBtn').disabled=true;$('mobileScanBtn').textContent='Scanning…'}
  addActivity(`Full scan started: ${state.account.broker} ${state.account.accountNumber}.`);
  try{
    const r=await fetch('/api/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({account_id:state.account.id})});
    if(!r.ok)throw new Error('backend scan failed');
    const data=await r.json();
    const rows=data.results||[];
    if(rows.length){state.account.symbols=rows.map(x=>[x.symbol,'Broker',Number(x.proposal?.entry||1)]);}
    state.scanResults=rows;
    state.top3=rows.slice(0,3).map(row=>({...row,normalized:normalizeBackendProposal(row)}));
    renderTop3();
    const top=rows[0];
    if(!top)throw new Error('no scan results');
    let s=state.account.symbols.find(x=>x[0]===top.symbol);
    if(!s)s=[top.symbol,top.assetClass||'Broker',Number(top.proposal?.entry||1)];
    let bundle=makeBundle(s);
    try{const cr=await fetch('/api/chart/'+encodeURIComponent(top.symbol)+'?account_id='+encodeURIComponent(state.account.id));if(cr.ok){const cj=await cr.json();bundle={'4h':cj.bundle['4H'],'1h':cj.bundle['1H'],'15m':cj.bundle['15M'],'5m':cj.bundle['5M']};}}catch(e){}
    const bp=top.proposal;
    state.symbol=s;state.series=bundle;
    state.proposal=state.top3[0].normalized;
    const shortlist=rows.slice(0,3).map((x,i)=>`${i+1}. ${x.symbol} ${x.direction} ${x.score}%`).join(' · ');
    addChat('ai',`Connector scan complete for ${data.account.platform} account ${data.account.accountNumber}. I reviewed 4H, 1H, 15M and 5M candle/volume/RSI data for all ${data.symbolsScanned} broker symbols. Top setups: ${shortlist}. Loading ${top.symbol} for approval.`);
    addActivity('Scan executed through the backend connector path.','success');
    $('symbolTitle').textContent=s[0];$('priceTitle').textContent=fmt(bundle['5m'].at(-1).c,s[0]);renderWatchlist();drawAll();renderProposal();
  }catch(e){
    const results=state.account.symbols.map(s=>{const bundle=makeBundle(s);const proposal=createProposal(s,bundle);return{symbol:s[0],s,bundle,proposal,score:proposal.score,dir:proposal.dir}}).sort((a,b)=>b.score-a.score);
    const top=results[0];state.scanResults=results;state.top3=results.slice(0,3).map(r=>({symbol:r.symbol,assetClass:r.s[1],proposal:{symbol:r.proposal.symbol,direction:r.proposal.dir==='LONG'?'BUY':'SELL',score:r.proposal.score,entry:r.proposal.entry,safeLoss:r.proposal.stop,takeProfit1:r.proposal.tp1,takeProfit2:r.proposal.tp2,riskPercent:r.proposal.risk,proposalId:`${state.account.id}:${r.symbol}`,evidence:{rsis:{'4H':r.proposal.r4,'1H':r.proposal.r1,'15M':r.proposal.r15,'5M':r.proposal.r5},volumeRatio15m:r.proposal.volRatio}},normalized:r.proposal}));renderTop3();state.symbol=top.s;state.series=top.bundle;state.proposal=top.proposal;
    addChat('ai',`Local fallback scan complete for ${state.account.broker} account ${state.account.accountNumber}. Start server.py to exercise the connector-backed scan path.`);
    $('symbolTitle').textContent=top.s[0];$('priceTitle').textContent=fmt(top.bundle['5m'].at(-1).c,top.s[0]);renderWatchlist();drawAll();renderProposal();addActivity('Local browser fallback scan used.','warn');
  }finally{$('scanBtn').disabled=false;$('scanBtn').textContent='Scan Everything';if($('mobileScanBtn')){$('mobileScanBtn').disabled=false;$('mobileScanBtn').textContent='Scan Everything'}}
}
function addChat(role,text){const d=document.createElement('div');d.className='bubble '+role;d.innerHTML=`${text}<span class="time">${now()}</span>`;$('chatLog').appendChild(d);$('chatLog').scrollTop=$('chatLog').scrollHeight}
function addActivity(text,type=''){const d=document.createElement('div');d.className='activity '+type;d.textContent=`${now()} · ${text}`;$('activityLog').prepend(d)}
function populateAlertSymbols(){$('alertSymbol').innerHTML=state.account.symbols.map(s=>`<option>${s[0]}</option>`).join('')}
function saveAlert(){const symbol=$('alertSymbol').value,condition=$('alertCondition').value,level=parseFloat($('alertLevel').value);if(!Number.isFinite(level))return;state.alerts.push({symbol,condition,level});renderAccount();addChat('ai',`Alert created for ${symbol}: ${condition} ${level}. A production trigger would request fresh charts and let the connected ChatGPT conversation re-run analysis.`);addActivity(`Alert created: ${symbol} ${condition} ${level}.`,'success')}
function handleChat(text){addChat('user',text);const t=text.toLowerCase();if(t.includes('scan')){scan();return}if(t.includes('explain')){explain();return}if(t.includes('approve')){approve(t.includes('explain'));return}if(t.includes('account')){addChat('ai',`Active route is ${state.account.broker} account ${state.account.accountNumber} (${state.account.environment}).`);return}if(t.includes('alert')){$('newAlertBtn').click();return}const symbol=state.account.symbols.find(s=>t.includes(s[0].toLowerCase()));if(symbol){selectSymbol(symbol);return}if(t.includes('open')||t.includes('position')){addChat('ai',`Account ${state.account.accountNumber} currently shows ${state.open} simulated open position(s) and ${state.pending} pending order(s).`);return}addChat('ai',`Demo command understood. Try “scan everything”, “what account am I using?”, “explain this trade”, “approve this trade”, or type a symbol from this account's broker watchlist.`)}

const tl=accounts.filter(a=>a.platform==='TL').map(a=>`<option value="${a.id}">${a.name}</option>`).join('');
const mt=accounts.filter(a=>a.platform==='MT5').map(a=>`<option value="${a.id}">${a.name}</option>`).join('');
$('accountSelect').innerHTML=`<optgroup label="TradeLocker Accounts">${tl}</optgroup><optgroup label="MetaTrader 5 Accounts">${mt}</optgroup>`;
$('accountSelect').onchange=loadAccount;$('scanBtn').onclick=scan;$('refreshBtn').onclick=()=>{renderWatchlist();addActivity(`Broker symbols refreshed for account ${state.account.accountNumber}.`)};$('expBtn').onclick=explain;$('appBtn').onclick=()=>approve(false);$('expAppBtn').onclick=()=>approve(true);$('rejectBtn').onclick=reject;$('newAlertBtn').onclick=()=>{$('alertSymbol').value=state.symbol?.[0]||state.account.symbols[0][0];$('alertLevel').value=state.symbol?.[2]||'';$('alertDialog').showModal()};$('saveAlertBtn').onclick=saveAlert;$('chatForm').onsubmit=e=>{e.preventDefault();const v=$('chatInput').value.trim();if(v){handleChat(v);$('chatInput').value=''}};$('connectBtn').onclick=()=>{$('accountDialogTitle').textContent=`${state.account.broker} · Account ${state.account.accountNumber}`;$('accountDialogBody').innerHTML=`<div class="risk-row"><span>Platform</span><strong>${state.account.broker}</strong></div><div class="risk-row"><span>Account number</span><strong>${state.account.accountNumber}</strong></div><div class="risk-row"><span>Environment</span><strong>${state.account.environment} / simulated</strong></div><div class="risk-row"><span>Watchlist source</span><strong>${state.account.platform==='MT5'?'MetaTrader Market Watch':'TradeLocker broker instrument list'}</strong></div><div class="risk-row"><span>Symbols available</span><strong>${state.account.symbols.length}</strong></div><div class="notice">No real broker credentials are stored in this demo. Production connections use encrypted broker credentials/tokens and every order is explicitly routed by platform + account number.</div>`;$('accountDialog').showModal()};$('closeAccountDialog').onclick=()=>$('accountDialog').close();$('testConnectorBtn').onclick=async()=>{try{const r=await fetch('/health');const j=await r.json();state.connector.tested=!!j.ok;renderConversationStatus();$('conversationNote').textContent=j.ok?`Connector backend is responding (${j.version}). When exposed as a supported ChatGPT custom app, your existing conversation can call /mcp tools directly.`:'Connector test failed.';addActivity(j.ok?'Connector backend test passed.':'Connector backend test failed.',j.ok?'success':'warn')}catch(e){state.connector.tested=false;renderConversationStatus();$('conversationNote').textContent='Open this demo through server.py to test the MCP backend; direct file opening only runs the browser simulation.';addActivity('Connector backend unavailable. Start server.py.','warn')}};$('showToolsBtn').onclick=async()=>{try{const r=await fetch('/mcp-tools');const j=await r.json();addChat('ai','MCP tools: '+j.tools.map(t=>t.name).join(', '));}catch(e){addChat('ai','Start server.py first, then this button will show the MCP tool catalog.')}};window.addEventListener('resize',()=>state.series['4h']&&drawAll());
if($('mobileScanBtn'))$('mobileScanBtn').onclick=scan;if($('mobileTop3Btn'))$('mobileTop3Btn').onclick=()=>$('top3Section')?.scrollIntoView({behavior:'smooth',block:'start'});if($('mobileChartsBtn'))$('mobileChartsBtn').onclick=()=>document.querySelector('.chart-card')?.scrollIntoView({behavior:'smooth',block:'start'});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;$('installBtn')?.classList.remove('hidden')});if($('installBtn'))$('installBtn').onclick=async()=>{if(!state.installPrompt){addChat('ai','Install becomes available when this PWA is served from localhost or HTTPS in a supported browser.');return}state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;$('installBtn').classList.add('hidden')};if('serviceWorker' in navigator && location.protocol!=='file:'){window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(()=>{}))}

async function syncBackendAccounts(){
  try{
    const r=await fetch('/api/accounts'); if(!r.ok)return; const data=await r.json();
    const backend=data.accounts||[];
    backend.forEach(a=>{
      const existing=accounts.find(x=>x.id===a.id);
      if(existing){existing.accountNumber=a.account_number;existing.environment=a.environment;return}
      accounts.push({id:a.id,platform:a.platform==='TradeLocker'?'TL':'MT5',broker:a.platform,accountNumber:a.account_number,environment:a.environment,name:`${a.platform} · Account ${a.account_number}`,balance:0,equity:0,dailyPl:0,symbols:[['Run Scan','Broker',1]]});
    });
    const tl=accounts.filter(a=>a.platform==='TL').map(a=>`<option value="${a.id}">${a.name}</option>`).join('');
    const mt=accounts.filter(a=>a.platform==='MT5').map(a=>`<option value="${a.id}">${a.name}</option>`).join('');
    $('accountSelect').innerHTML=`<optgroup label="TradeLocker Accounts">${tl}</optgroup><optgroup label="MetaTrader 5 Accounts">${mt}</optgroup>`;
    if(data.active?.id && accounts.some(x=>x.id===data.active.id)) $('accountSelect').value=data.active.id;
    await loadAccount();
  }catch(e){}
}
function showBrokerStatus(text,ok=true){const el=$('brokerConnectStatus');el.textContent=text;el.classList.remove('hidden');el.className='notice '+(ok?'':'warn')}
if($('brokerConnectBtn'))$('brokerConnectBtn').onclick=()=>$('brokerDialog').showModal();
if($('closeBrokerDialog'))$('closeBrokerDialog').onclick=()=>$('brokerDialog').close();
if($('tlConnectForm'))$('tlConnectForm').onsubmit=async e=>{e.preventDefault();showBrokerStatus('Connecting to TradeLocker…');const f=Object.fromEntries(new FormData(e.target).entries());try{const r=await fetch('/api/connect/tradelocker',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(f)});const j=await r.json();if(!r.ok)throw new Error(j.detail||'Connection failed');showBrokerStatus('TradeLocker connected. Accounts discovered and stored securely.');await syncBackendAccounts()}catch(err){showBrokerStatus(err.message,false)}};
if($('mt5ConnectForm'))$('mt5ConnectForm').onsubmit=async e=>{e.preventDefault();showBrokerStatus('Connecting to MetaTrader 5…');const f=Object.fromEntries(new FormData(e.target).entries());f.environment='DEMO';try{const r=await fetch('/api/connect/mt5',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(f)});const j=await r.json();if(!r.ok)throw new Error(j.detail||'Connection failed');showBrokerStatus('MetaTrader 5 connected. Account discovered.');await syncBackendAccounts()}catch(err){showBrokerStatus(err.message,false)}};
loadAccount();syncBackendAccounts();renderConversationStatus();addChat('ai','App ready. Connect a TradeLocker demo account or an MT5 terminal, select the exact account, then use Scan Everything to rank the top three setups. The MCP endpoint exposes the same tools for ChatGPT integration.');
